FROM gliderlabs/alpine:3.2
MAINTAINER Jimmi Dyson <jimmidyson@gmail.com>
EXPOSE 3000

ENV GOPATH /go
ENV PATH ${GOPATH}/bin:${PATH}
RUN apk-install go git mercurial tar gzip

ENV GRAFANA_VERSION 1.9.1
ENV INFLUXDB_NAME k8s
ENV GRAFANA_DB_NAME grafana
ENV GRAFANA_DEFAULT_DASHBOARD /dashboard/file/default.json
ENV INFLUXDB_PROTO http
ENV INFLUXDB_USER root
ENV INFLUXDB_PASSWORD root

RUN mkdir /opt && \
    wget -q -O - http://grafanarel.s3.amazonaws.com/grafana-${GRAFANA_VERSION}.tar.gz | gzip -dc | tar xv -C /opt && \
    mv /opt/grafana-${GRAFANA_VERSION} /opt/grafana

COPY config.js.tmpl /opt/grafana/config.js.tmpl
COPY kubernetes-dashboard.json /opt/grafana/app/dashboards/kubernetes.json

WORKDIR ${GOPATH}/src/github.com/fabric8io/grafana
CMD go build -ldflags "-X main.Version dev" -o /opt/grafana/grafana \
  && cd /opt/grafana && exec /opt/grafana/grafana
